"""
Creates the complete Item Master App database schema in one pass: every
table, column, default, primary key, unique rule, check rule, index and
foreign key, plus the two required seed rows (dept_mapping_config,
dept_push_approvals).

This is the ONE file to run to stand up the database from nothing:

    python migrations/001_create_schema.py

It was generated by reading the live database's actual schema (so it
matches exactly what the app runs against), and it replaces the earlier
step-by-step migrations (002-009: discard-notice group labels, complete
snapshots, last-seen tracking, the Undo action log, snapshot kinds, merge
"added items", per-person workspace, the app error log) — they're all
folded in here.

Every statement is guarded (IF NOT EXISTS), so it's safe to run against an
empty database or an already-current one. To wipe a database and rebuild
it, use scripts/reset_schema.py (destructive). A future schema change can
go in a new 002_*.py migration, then be folded back in here the same way.
"""

import sys
from pathlib import Path

from sqlalchemy import text

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from itemmaster.db import get_engine  # noqa: E402

TABLES = [
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'app_errors' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.app_errors (
        error_id               INT IDENTITY(1,1) NOT NULL,
        occurred_at            DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        username               NVARCHAR(200),
        where_in_app           NVARCHAR(300),
        error_type             NVARCHAR(200),
        message                NVARCHAR(4000),
        details                NVARCHAR(MAX),
        resolved_by            NVARCHAR(200),
        resolved_at            DATETIME2,
        CONSTRAINT PK__app_erro__DA71E16C180B35DE PRIMARY KEY (error_id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'change_discard_notices' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.change_discard_notices (
        id                     INT IDENTITY(1,1) NOT NULL,
        entity_type            VARCHAR(20) NOT NULL,
        entity_label           NVARCHAR(400) NOT NULL,
        originally_staged_by   NVARCHAR(200),
        reason                 NVARCHAR(400) NOT NULL,
        triggered_by           NVARCHAR(200),
        triggered_at           DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        dismissed              BIT NOT NULL DEFAULT 0,
        group_label            NVARCHAR(400),
        CONSTRAINT PK__change_d__3213E83F452CD531 PRIMARY KEY (id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'deleted_upcs' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.deleted_upcs (
        upc                    VARCHAR(12) NOT NULL,
        deleted_by             VARCHAR(100),
        deleted_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        description            NVARCHAR(500),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        CONSTRAINT PK__deleted___DD77EB42ADD78F16 PRIMARY KEY (upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_action_log' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_action_log (
        action_id              BIGINT IDENTITY(1,1) NOT NULL,
        actor                  NVARCHAR(200) NOT NULL,
        combo_id               BIGINT NOT NULL,
        label                  NVARCHAR(600) NOT NULL,
        description            NVARCHAR(400) NOT NULL,
        before_json            NVARCHAR(MAX) NOT NULL,
        after_json             NVARCHAR(MAX) NOT NULL,
        status                 VARCHAR(10) NOT NULL DEFAULT 'done',
        created_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        changed_at             DATETIME2,
        click_id               VARCHAR(40),
        CONSTRAINT PK_dept_mapping_action_log PRIMARY KEY (action_id)
    );
    CREATE INDEX IX_action_log_actor ON dbo.dept_mapping_action_log(actor, status, action_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_broken_out_claims' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_broken_out_claims (
        combo_id               INT NOT NULL,
        claimed_by             NVARCHAR(200) NOT NULL,
        claimed_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        last_activity_at       DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_broken_out_claims PRIMARY KEY (combo_id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combo_agreements' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combo_agreements (
        combo_id               INT NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        agreed_by              NVARCHAR(200) NOT NULL,
        agreed_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_combo_agreements PRIMARY KEY (combo_id, department, agreed_by)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combo_suggestions' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combo_suggestions (
        combo_id               INT NOT NULL,
        staged_by              NVARCHAR(200) NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        tier                   VARCHAR(20),
        source_key             VARCHAR(50),
        label                  NVARCHAR(400),
        n_upcs_total           INT,
        suggested_at           DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_combo_suggestions PRIMARY KEY (combo_id, staged_by)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combo_upcs' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combo_upcs (
        combo_id               BIGINT NOT NULL,
        upc                    VARCHAR(12) NOT NULL,
        is_evidence            BIT NOT NULL DEFAULT 0,
        p1_department          NVARCHAR(200),
        CONSTRAINT PK__dept_map__2520341703FE6A63 PRIMARY KEY (combo_id, upc)
    );
    CREATE INDEX IX_dept_mapping_combo_upcs_upc ON dbo.dept_mapping_combo_upcs(upc);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combo_upcs_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combo_upcs_snapshot (
        snapshot_id            INT NOT NULL,
        combo_id               BIGINT NOT NULL,
        upc                    VARCHAR(20) NOT NULL,
        is_evidence            BIT,
        p1_department          NVARCHAR(200)
    );
    CREATE INDEX IX_combo_upcs_snapshot_snapshot_id ON dbo.dept_mapping_combo_upcs_snapshot(snapshot_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combos' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combos (
        combo_id               BIGINT IDENTITY(1,1) NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        raw_department         NVARCHAR(200) NOT NULL,
        raw_category           NVARCHAR(200) NOT NULL,
        raw_subcategory        NVARCHAR(200) NOT NULL,
        n_upcs_total           INT NOT NULL DEFAULT 0,
        n_evidence             INT NOT NULL DEFAULT 0,
        purity                 FLOAT,
        majority_department    NVARCHAR(200),
        suggested_department   NVARCHAR(200),
        tier                   VARCHAR(20) NOT NULL DEFAULT 'unmatched',
        resolved_via           NVARCHAR(400),
        chain_round            TINYINT,
        is_strict              BIT NOT NULL DEFAULT 0,
        manual_department      NVARCHAR(200),
        approved               BIT NOT NULL DEFAULT 0,
        rejected               BIT NOT NULL DEFAULT 0,
        decision_state         VARCHAR(30) NOT NULL DEFAULT 'not_reviewed',
        decided_department     NVARCHAR(200),
        decided_via            VARCHAR(30),
        is_new_this_run        BIT NOT NULL DEFAULT 1,
        is_stale               BIT NOT NULL DEFAULT 0,
        first_seen_at          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        last_computed_at       DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        last_decided_at        DATETIME2,
        last_decided_by        VARCHAR(100),
        runner_up_department   NVARCHAR(200),
        runner_up_share        FLOAT,
        pushed_by              NVARCHAR(200),
        pushed_at              DATETIME2,
        CONSTRAINT PK__dept_map__18F74AA3C03F14FA PRIMARY KEY (combo_id),
        CONSTRAINT UQ_dept_mapping_combo UNIQUE (source_key, raw_department, raw_category, raw_subcategory)
    );
    CREATE INDEX IX_dept_mapping_combos_source ON dbo.dept_mapping_combos(source_key);
    CREATE INDEX IX_dept_mapping_combos_tier ON dbo.dept_mapping_combos(tier, decision_state);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_combos_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_combos_snapshot (
        snapshot_id            INT NOT NULL,
        combo_id               BIGINT NOT NULL,
        source_key             VARCHAR(50),
        raw_department         NVARCHAR(200),
        raw_category           NVARCHAR(200),
        raw_subcategory        NVARCHAR(200),
        tier                   VARCHAR(20),
        purity                 FLOAT,
        n_evidence             INT,
        resolved_via           NVARCHAR(400),
        decision_state         VARCHAR(30),
        decided_department     NVARCHAR(200),
        decided_via            VARCHAR(30),
        majority_department    NVARCHAR(200),
        chain_round            INT,
        is_strict              BIT,
        manual_department      NVARCHAR(200),
        approved               BIT,
        rejected               BIT,
        is_new_this_run        BIT,
        is_stale               BIT,
        first_seen_at          DATETIME2,
        last_computed_at       DATETIME2,
        last_decided_at        DATETIME2,
        last_decided_by        VARCHAR(100),
        runner_up_department   NVARCHAR(200),
        runner_up_share        FLOAT,
        n_upcs_total           INT,
        suggested_department   NVARCHAR(200),
        pushed_by              NVARCHAR(200),
        pushed_at              DATETIME2,
        CONSTRAINT PK__dept_map__E3F38F5DEE083BFF PRIMARY KEY (snapshot_id, combo_id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_config' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_config (
        config_id              INT NOT NULL DEFAULT 1,
        min_purity             FLOAT NOT NULL DEFAULT 0.90,
        min_sample             INT NOT NULL DEFAULT 5,
        max_chain_rounds       TINYINT NOT NULL DEFAULT 3,
        cat_match2_min_siblings INT NOT NULL DEFAULT 2,
        brand_combo_min_sample INT NOT NULL DEFAULT 5,
        brand_combo_min_purity FLOAT NOT NULL DEFAULT 0.90,
        brand_item_min_sample  INT NOT NULL DEFAULT 1,
        brand_item_min_purity  FLOAT NOT NULL DEFAULT 0.75,
        brand_category_consensus_min_sample INT NOT NULL DEFAULT 15,
        brand_keyword_conflict_max_fraction FLOAT NOT NULL DEFAULT 0.20,
        CONSTRAINT PK__dept_map__4AD1BFF1D86E8813 PRIMARY KEY (config_id),
        CONSTRAINT CK_dept_mapping_config_single_row CHECK ([config_id]=(1))
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_departments' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_departments (
        department             NVARCHAR(200) NOT NULL,
        source_type            VARCHAR(20) NOT NULL,
        added_at               DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK__dept_map__3F4ABF822964FD64 PRIMARY KEY (department)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_keyword_rules' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_keyword_rules (
        rule_id                INT IDENTITY(1,1) NOT NULL,
        keyword                NVARCHAR(200) NOT NULL,
        match_field            VARCHAR(20) NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        CONSTRAINT PK__dept_map__E92A9296BD8F7E06 PRIMARY KEY (rule_id),
        CONSTRAINT CK_dept_mapping_keyword_rules_field CHECK ([match_field]='description_word' OR [match_field]='subcategory' OR [match_field]='category')
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_pending_changes' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_pending_changes (
        combo_id               BIGINT NOT NULL,
        tier                   VARCHAR(20),
        department             NVARCHAR(200) NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        label                  NVARCHAR(600) NOT NULL,
        n_upcs_total           INT NOT NULL,
        staged_by              VARCHAR(100) NOT NULL,
        staged_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        is_saved               BIT NOT NULL DEFAULT 0,
        agreed_by              NVARCHAR(200),
        agreed_at              DATETIME2,
        overridden_by          NVARCHAR(200),
        overridden_at          DATETIME2,
        CONSTRAINT PK__dept_map__18F74AA38D76C1B0 PRIMARY KEY (combo_id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_pending_changes_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_pending_changes_snapshot (
        snapshot_id            INT NOT NULL,
        combo_id               BIGINT NOT NULL,
        tier                   VARCHAR(20),
        department             NVARCHAR(200),
        source_key             VARCHAR(50),
        label                  NVARCHAR(600),
        n_upcs_total           INT,
        staged_by              VARCHAR(100),
        staged_at              DATETIME2,
        is_saved               BIT
    );
    CREATE INDEX IX_dept_pending_snapshot_snapshot_id ON dbo.dept_mapping_pending_changes_snapshot(snapshot_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_pending_upc_changes' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_pending_upc_changes (
        upc                    VARCHAR(20) NOT NULL,
        combo_id               BIGINT NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        label                  NVARCHAR(600) NOT NULL,
        description            NVARCHAR(400),
        source_key             VARCHAR(50) NOT NULL,
        staged_by              VARCHAR(100) NOT NULL,
        staged_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        is_saved               BIT NOT NULL DEFAULT 0,
        agreed_by              NVARCHAR(200),
        agreed_at              DATETIME2,
        overridden_by          NVARCHAR(200),
        overridden_at          DATETIME2,
        revised_by             NVARCHAR(200),
        revised_at             DATETIME2,
        CONSTRAINT PK_dept_mapping_pending_upc_changes PRIMARY KEY (upc, staged_by)
    );
    CREATE INDEX IX_dept_mapping_pending_upc_changes_combo_id ON dbo.dept_mapping_pending_upc_changes(combo_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_pending_upc_changes_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_pending_upc_changes_snapshot (
        snapshot_id            INT NOT NULL,
        upc                    VARCHAR(20) NOT NULL,
        combo_id               BIGINT,
        department             NVARCHAR(200),
        label                  NVARCHAR(600),
        description            NVARCHAR(400),
        source_key             VARCHAR(50),
        staged_by              VARCHAR(100),
        staged_at              DATETIME2,
        is_saved               BIT
    );
    CREATE INDEX IX_dept_upc_pending_snapshot_snapshot_id ON dbo.dept_mapping_pending_upc_changes_snapshot(snapshot_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_recent_moves' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_recent_moves (
        move_id                BIGINT IDENTITY(1,1) NOT NULL,
        combo_id               BIGINT NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        label                  NVARCHAR(600) NOT NULL,
        n_upcs_total           INT NOT NULL,
        description            NVARCHAR(200) NOT NULL,
        snapshot_json          NVARCHAR(MAX) NOT NULL,
        created_by             VARCHAR(100) NOT NULL,
        created_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK__dept_map__2037E4BDF411048B PRIMARY KEY (move_id)
    );
    CREATE INDEX IX_dept_mapping_recent_moves_combo_id ON dbo.dept_mapping_recent_moves(combo_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_snapshot_tables' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_snapshot_tables (
        snapshot_id            INT NOT NULL,
        table_name             VARCHAR(100) NOT NULL,
        rows_json              NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_dept_mapping_snapshot_tables PRIMARY KEY (snapshot_id, table_name)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_snapshots' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_snapshots (
        snapshot_id            INT IDENTITY(1,1) NOT NULL,
        snapshot_month         CHAR(7) NOT NULL,
        taken_at               DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        item_count             INT NOT NULL,
        combo_count            INT NOT NULL,
        label                  NVARCHAR(200),
        taken_by               VARCHAR(100),
        kind                   VARCHAR(20) NOT NULL DEFAULT 'manual',
        restored_from          INT,
        details_json           NVARCHAR(MAX),
        CONSTRAINT PK__dept_map__C27CFBF7646ACF7C PRIMARY KEY (snapshot_id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_strict_departments' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_strict_departments (
        strict_id              INT IDENTITY(1,1) NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        old_department         NVARCHAR(200) NOT NULL,
        trust_direct_evidence  BIT NOT NULL DEFAULT 0,
        updated_by             VARCHAR(100),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK__dept_map__D4C7798534B53337 PRIMARY KEY (strict_id),
        CONSTRAINT UQ_dept_mapping_strict_department UNIQUE (source_key, old_department)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_undo_requests' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_undo_requests (
        entity_type            VARCHAR(10) NOT NULL,
        entity_id              NVARCHAR(50) NOT NULL,
        requested_by           NVARCHAR(200) NOT NULL,
        requested_at           DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_undo_requests PRIMARY KEY (entity_type, entity_id, requested_by)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_unmatched_defaults' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_unmatched_defaults (
        default_id             INT IDENTITY(1,1) NOT NULL,
        source_key             VARCHAR(50),
        old_department         NVARCHAR(200) NOT NULL,
        new_department         NVARCHAR(200) NOT NULL,
        updated_by             VARCHAR(100),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK__dept_map__170AD430AAB11842 PRIMARY KEY (default_id),
        CONSTRAINT UQ_dept_mapping_unmatched_default UNIQUE (source_key, old_department)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_upc_agreements' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_upc_agreements (
        upc                    VARCHAR(20) NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        agreed_by              NVARCHAR(200) NOT NULL,
        agreed_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_upc_agreements PRIMARY KEY (upc, department, agreed_by)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_upc_change_suggestions' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_upc_change_suggestions (
        upc                    VARCHAR(20) NOT NULL,
        suggested_by           NVARCHAR(200) NOT NULL,
        department             NVARCHAR(200) NOT NULL,
        combo_id               INT,
        label                  NVARCHAR(400),
        description            NVARCHAR(400),
        source_key             VARCHAR(50),
        suggested_at           DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_dept_mapping_upc_change_suggestions PRIMARY KEY (upc, suggested_by)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_upc_overrides' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_upc_overrides (
        upc                    VARCHAR(12) NOT NULL,
        combo_id               BIGINT NOT NULL,
        suggested_department   NVARCHAR(200),
        suggested_via          NVARCHAR(300),
        department             NVARCHAR(200),
        decided_via            NVARCHAR(300) NOT NULL DEFAULT 'not_reviewed',
        updated_by             VARCHAR(100),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        pushed_by              NVARCHAR(200),
        pushed_at              DATETIME2,
        CONSTRAINT PK__dept_map__DD77EB4268EA6726 PRIMARY KEY (upc)
    );
    CREATE INDEX IX_dept_mapping_upc_overrides_combo ON dbo.dept_mapping_upc_overrides(combo_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_mapping_upc_overrides_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_mapping_upc_overrides_snapshot (
        snapshot_id            INT NOT NULL,
        upc                    VARCHAR(12) NOT NULL,
        combo_id               BIGINT,
        department             NVARCHAR(200),
        decided_via            NVARCHAR(300),
        suggested_department   NVARCHAR(200),
        suggested_via          NVARCHAR(300),
        updated_by             VARCHAR(100),
        updated_at             DATETIME2,
        pushed_by              NVARCHAR(200),
        pushed_at              DATETIME2,
        CONSTRAINT PK__dept_map__FFAB85432CAF0891 PRIMARY KEY (snapshot_id, upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'dept_push_approvals' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.dept_push_approvals (
        id                     INT NOT NULL,
        approvals              NVARCHAR(MAX),
        CONSTRAINT PK__dept_pus__3213E83FD7BF6A3D PRIMARY KEY (id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ingestion_log' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ingestion_log (
        id                     BIGINT IDENTITY(1,1) NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        uploaded_at            DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        uploaded_by            VARCHAR(100),
        original_filename      VARCHAR(300),
        rows_parsed            INT NOT NULL,
        rows_staged            INT NOT NULL,
        dropped_invalid_upc    INT NOT NULL DEFAULT 0,
        dropped_duplicate_upc  INT NOT NULL DEFAULT 0,
        CONSTRAINT PK__ingestio__3213E83FAB0F9E3D PRIMARY KEY (id)
    );
    CREATE INDEX ix_ingestion_log_source ON dbo.ingestion_log(source_key, uploaded_at);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ingestion_rejected_rows' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.ingestion_rejected_rows (
        id                     BIGINT IDENTITY(1,1) NOT NULL,
        log_id                 BIGINT NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        reason                 VARCHAR(30) NOT NULL,
        raw_upc                VARCHAR(200),
        department             VARCHAR(200),
        category               VARCHAR(200),
        subcategory            VARCHAR(200),
        brand                  VARCHAR(200),
        description            VARCHAR(500),
        CONSTRAINT PK__ingestio__3213E83FC028A894 PRIMARY KEY (id)
    );
    CREATE INDEX ix_ingestion_rejected_log ON dbo.ingestion_rejected_rows(log_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'item_master_pending_changes' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.item_master_pending_changes (
        upc                    VARCHAR(20) NOT NULL,
        change_type            VARCHAR(10) NOT NULL,
        description            NVARCHAR(400),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        is_saved               BIT NOT NULL DEFAULT 0,
        staged_by              VARCHAR(100) NOT NULL,
        staged_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        source_key             VARCHAR(50),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        CONSTRAINT PK__item_mas__DD77EB429975099C PRIMARY KEY (upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'item_master_pending_changes_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.item_master_pending_changes_snapshot (
        snapshot_id            INT NOT NULL,
        upc                    VARCHAR(20) NOT NULL,
        change_type            VARCHAR(10) NOT NULL,
        description            NVARCHAR(400),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        is_saved               BIT,
        staged_by              VARCHAR(100),
        staged_at              DATETIME2,
        source_key             VARCHAR(50),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50)
    );
    CREATE INDEX IX_item_master_pending_snapshot_snapshot_id ON dbo.item_master_pending_changes_snapshot(snapshot_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'items' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.items (
        upc                    VARCHAR(12) NOT NULL,
        description            NVARCHAR(500) NOT NULL,
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        source_key             VARCHAR(50),
        created_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        CONSTRAINT PK__items__DD77EB4206727A7A PRIMARY KEY (upc)
    );
    CREATE INDEX ix_items_brand ON dbo.items(brand);
    CREATE INDEX ix_items_department ON dbo.items(department);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'items_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.items_snapshot (
        snapshot_id            INT NOT NULL,
        upc                    VARCHAR(12) NOT NULL,
        description            NVARCHAR(500),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        source_key             VARCHAR(50),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        created_at             DATETIME2,
        updated_at             DATETIME2,
        CONSTRAINT PK__items_sn__FFAB854389E85E1C PRIMARY KEY (snapshot_id, upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'items_staged' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.items_staged (
        upc                    VARCHAR(12) NOT NULL,
        description            NVARCHAR(500),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        source_key             VARCHAR(50),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        CONSTRAINT PK__items_st__DD77EB42481601B7 PRIMARY KEY (upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'manual_overrides' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.manual_overrides (
        upc                    VARCHAR(12) NOT NULL,
        description            NVARCHAR(500),
        department             NVARCHAR(200),
        category               NVARCHAR(200),
        subcategory            NVARCHAR(200),
        brand                  NVARCHAR(200),
        updated_by             VARCHAR(100),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        pack                   NVARCHAR(100),
        size                   NVARCHAR(100),
        uom                    NVARCHAR(50),
        CONSTRAINT PK__manual_o__DD77EB427930130F PRIMARY KEY (upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'merge_added_items' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.merge_added_items (
        merge_id               INT NOT NULL,
        upc                    VARCHAR(12) NOT NULL,
        CONSTRAINT PK_merge_added_items PRIMARY KEY (merge_id, upc)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'merge_compute_meta' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.merge_compute_meta (
        computed_at            DATETIME2 NOT NULL,
        computed_by            VARCHAR(100),
        item_count             INT NOT NULL,
        overrides_applied      INT NOT NULL,
        deleted_excluded       INT NOT NULL,
        added_count            INT,
        changed_count          INT,
        removed_count          INT,
        changed_by_field       NVARCHAR(MAX),
        changed_by_source      NVARCHAR(MAX),
        approvals              NVARCHAR(MAX)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'merge_log' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.merge_log (
        id                     INT IDENTITY(1,1) NOT NULL,
        merged_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        merged_by              VARCHAR(100),
        upc_count              INT,
        added_count            INT,
        changed_count          INT,
        removed_count          INT,
        overrides_applied      INT,
        deleted_excluded       INT,
        source_breakdown       NVARCHAR(MAX),
        changed_by_field       NVARCHAR(MAX),
        changed_by_source      NVARCHAR(MAX),
        CONSTRAINT PK__merge_lo__3213E83F28ED51A5 PRIMARY KEY (id)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'raw_items' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.raw_items (
        upc                    VARCHAR(12) NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        department             VARCHAR(200),
        category               VARCHAR(200),
        subcategory            VARCHAR(200),
        brand                  VARCHAR(200),
        description            VARCHAR(500),
        loaded_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        pack                   VARCHAR(100),
        size                   VARCHAR(100),
        uom                    VARCHAR(50),
        CONSTRAINT PK__raw_item__F58CF394F2F1143C PRIMARY KEY (upc, source_key)
    );
    CREATE INDEX ix_raw_items_source ON dbo.raw_items(source_key);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'source_pending_changes' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.source_pending_changes (
        source_key             VARCHAR(50) NOT NULL,
        change_type            VARCHAR(10) NOT NULL,
        apply_now              BIT NOT NULL DEFAULT 0,
        source_label           VARCHAR(100),
        enabled                BIT,
        priority_rank          INT,
        file_keyword           VARCHAR(200),
        sheet_name             VARCHAR(100),
        header_row             INT,
        upc_column             VARCHAR(100),
        upc_suffix_column      VARCHAR(100),
        strip_trailing_digits  INT,
        department_column      VARCHAR(100),
        category_column        VARCHAR(100),
        subcategory_column     VARCHAR(100),
        brand_column           VARCHAR(100),
        description_column     VARCHAR(100),
        pack_column            VARCHAR(100),
        size_column            VARCHAR(100),
        size_format            VARCHAR(30),
        uom_column             VARCHAR(100),
        exclude_column         VARCHAR(100),
        exclude_values         VARCHAR(500),
        blank_brand_when_equals VARCHAR(200),
        blank_department_when_equals VARCHAR(200),
        blank_department_default VARCHAR(200),
        brand_suffix_match     VARCHAR(50),
        brand_suffix_result    VARCHAR(50),
        dedup_deprioritize_brand_value VARCHAR(200),
        strip_leading_code_fields VARCHAR(200),
        notes                  VARCHAR(500),
        staged_by              VARCHAR(100),
        staged_at              DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        uom_aliases            VARCHAR(500),
        CONSTRAINT PK__source_p__8FB18D63D353B0B6 PRIMARY KEY (source_key)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'source_pending_changes_snapshot' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.source_pending_changes_snapshot (
        snapshot_id            INT NOT NULL,
        source_key             VARCHAR(50) NOT NULL,
        change_type            VARCHAR(10) NOT NULL,
        apply_now              BIT NOT NULL,
        source_label           VARCHAR(100),
        enabled                BIT,
        priority_rank          INT,
        file_keyword           VARCHAR(200),
        sheet_name             VARCHAR(100),
        header_row             INT,
        upc_column             VARCHAR(100),
        upc_suffix_column      VARCHAR(100),
        strip_trailing_digits  INT,
        department_column      VARCHAR(100),
        category_column        VARCHAR(100),
        subcategory_column     VARCHAR(100),
        brand_column           VARCHAR(100),
        description_column     VARCHAR(100),
        pack_column            VARCHAR(100),
        size_column            VARCHAR(100),
        size_format            VARCHAR(30),
        uom_column             VARCHAR(100),
        exclude_column         VARCHAR(100),
        exclude_values         VARCHAR(500),
        blank_brand_when_equals VARCHAR(200),
        blank_department_when_equals VARCHAR(200),
        blank_department_default VARCHAR(200),
        brand_suffix_match     VARCHAR(50),
        brand_suffix_result    VARCHAR(50),
        dedup_deprioritize_brand_value VARCHAR(200),
        strip_leading_code_fields VARCHAR(200),
        notes                  VARCHAR(500),
        staged_by              VARCHAR(100),
        staged_at              DATETIME2,
        uom_aliases            VARCHAR(500)
    );
    CREATE INDEX IX_source_pending_snapshot_snapshot_id ON dbo.source_pending_changes_snapshot(snapshot_id);
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'source_raw_uploads' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.source_raw_uploads (
        source_key             VARCHAR(50) NOT NULL,
        filename               NVARCHAR(400),
        raw_csv                NVARCHAR(MAX) NOT NULL,
        uploaded_by            VARCHAR(100),
        uploaded_at            DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK__source_r__8FB18D633A6AF15A PRIMARY KEY (source_key)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'sources' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.sources (
        source_key             VARCHAR(50) NOT NULL,
        source_label           VARCHAR(100) NOT NULL,
        enabled                BIT NOT NULL DEFAULT 1,
        priority_rank          INT NOT NULL,
        file_keyword           VARCHAR(200) NOT NULL,
        sheet_name             VARCHAR(100),
        header_row             INT NOT NULL DEFAULT 1,
        upc_column             VARCHAR(100) NOT NULL,
        upc_suffix_column      VARCHAR(100),
        strip_trailing_digits  INT NOT NULL DEFAULT 0,
        department_column      VARCHAR(100),
        category_column        VARCHAR(100),
        subcategory_column     VARCHAR(100),
        brand_column           VARCHAR(100),
        description_column     VARCHAR(100),
        notes                  VARCHAR(500),
        created_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        exclude_column         VARCHAR(100),
        exclude_values         VARCHAR(500),
        blank_brand_when_equals VARCHAR(200),
        blank_department_when_equals VARCHAR(200),
        blank_department_default VARCHAR(200),
        brand_suffix_match     VARCHAR(50),
        brand_suffix_result    VARCHAR(50),
        dedup_deprioritize_brand_value VARCHAR(200),
        strip_leading_code_fields VARCHAR(100),
        pack_column            VARCHAR(100),
        size_column            VARCHAR(100),
        uom_column             VARCHAR(100),
        size_format            VARCHAR(30) NOT NULL DEFAULT 'plain',
        uom_aliases            VARCHAR(500),
        CONSTRAINT PK__sources__8FB18D630A506CB5 PRIMARY KEY (source_key)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'user_last_seen' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.user_last_seen (
        username               NVARCHAR(200) NOT NULL,
        last_seen_at           DATETIME2 NOT NULL,
        CONSTRAINT PK_user_last_seen PRIMARY KEY (username)
    );
END
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'user_workspace' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.user_workspace (
        username               NVARCHAR(200) NOT NULL,
        item_key               NVARCHAR(300) NOT NULL,
        payload                NVARCHAR(MAX) NOT NULL,
        updated_at             DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_user_workspace PRIMARY KEY (username, item_key)
    );
END
    """
]

# Added after every table exists, so the tables above can be in any order.
FOREIGN_KEYS = [
    """
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('dbo.ingestion_log') AND referenced_object_id = OBJECT_ID('dbo.sources'))
    ALTER TABLE dbo.ingestion_log ADD CONSTRAINT FK_ingestion_log_source_key FOREIGN KEY (source_key) REFERENCES dbo.sources(source_key);
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('dbo.ingestion_rejected_rows') AND referenced_object_id = OBJECT_ID('dbo.ingestion_log'))
    ALTER TABLE dbo.ingestion_rejected_rows ADD CONSTRAINT FK_ingestion_rejected_rows_log_id FOREIGN KEY (log_id) REFERENCES dbo.ingestion_log(id);
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('dbo.raw_items') AND referenced_object_id = OBJECT_ID('dbo.sources'))
    ALTER TABLE dbo.raw_items ADD CONSTRAINT FK_raw_items_source_key FOREIGN KEY (source_key) REFERENCES dbo.sources(source_key);
    """,
    """
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('dbo.source_raw_uploads') AND referenced_object_id = OBJECT_ID('dbo.sources'))
    ALTER TABLE dbo.source_raw_uploads ADD CONSTRAINT FK_source_raw_uploads_source_key FOREIGN KEY (source_key) REFERENCES dbo.sources(source_key);
    """,
]

SEED_ROWS = """
IF NOT EXISTS (SELECT * FROM dbo.dept_mapping_config WHERE config_id = 1)
    INSERT INTO dbo.dept_mapping_config (config_id) VALUES (1);

IF NOT EXISTS (SELECT * FROM dbo.dept_push_approvals WHERE id = 1)
    INSERT INTO dbo.dept_push_approvals (id, approvals) VALUES (1, '[]');
"""


def statements() -> list:
    return TABLES + FOREIGN_KEYS + [SEED_ROWS]


def main():
    engine = get_engine()
    with engine.begin() as conn:
        for statement in statements():
            conn.execute(text(statement))
    print(f"Schema is ready: {len(TABLES)} tables, their indexes and foreign keys, and the seed rows "
          "(created, or already present).")


if __name__ == "__main__":
    main()
